version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  auth-service:
    build: ./services/auth
    container_name: auth-service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/interview_db
      - JWT_SECRET=your_jwt_secret_here
      - PORT=5001
    depends_on:
      - mongodb

  interview-service:
    build: ./services/interview
    container_name: interview-service
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/interview_db
      - JWT_SECRET=your_jwt_secret_here
      - API_KEY_GEMINI=your_gemini_api_key_here
      - PORT=5002
    depends_on:
      - mongodb

  frontend-service:
    build: ./services/frontend
    container_name: frontend-service
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - interview-service

volumes:
  mongo-data:
