apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Base64 encoded placeholders
  jwt-secret: eW91cl9qd3Rfc2VjcmV0X2hlcmU= # your_jwt_secret_here
  mongo-uri: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvaW50ZXJ2aWV3X2Ri # mongodb://mongodb:27017/interview_db
  groq-api-key: eW91cl9ncm9xX2FwaV9rZXlfaGVyZQ== # your_groq_api_key_here
